### ISSUE TITLE
Completing Manuscript

### ISSUE THREAD

**Issue by miladm12** [boettiger-lab/pomdp-intro#1]
@cboettig Two errors I noticed in the manuscript: 

- You say S = D = B_MSY which I think is not true. this should be S = D = max(0, B - B_MSY).

- you say U(x_t, a_t) = min(x_t - a_t ,0) which is not true: should be U(x_t,a_t) = min(x_t,a_t).

Also, I could not see in the new writings what are the changes in the needed figures to update them. The final figures are here: https://github.com/boettiger-lab/pomdp-fish/issues/84

Please let me know which ones needs to be changed. It would be great if we can finalize this at the same time as the RAM one and send them both out.

**Comment by cboettig** [comment]
@miladm12 Can you give another read through the current https://github.com/boettiger-lab/pomdp-intro/blob/master/manuscripts/manuscript.pdf and let me know if you find any errors, typos, or something that doesn't read well or sounds confusing?

**Comment by miladm12** [comment]
Sure I'll do it by tonight.

**Comment by cboettig** [comment]
Stuff for me to do tonight/tomorrow morning:

- [ ] Revise abstract (not just fisheries)
- [ ] Finish reply letter
- [ ] More explicit mention of Methods/code in manuscript
- [ ] final checks
